name: Schedule Automerge Run

on: 
  pull_request:
    types: [opened]
  
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10s
      - uses: actions/github-script@v6
        with:
          script: |
          github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "automerge_evaluate_pull_request.yml",
              context.ref,
          });


