name: Schedule Automerge Run

on:
  pull_request_target:
    types: [opened]
  workflow_dispatch:
    inputs:
      pull_request:
        required: true
        type: string

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: echo '${{ toJSON(github.event) }}'
      - name: Wait for Netlify test completion
        run: sleep 10m
      - uses: actions/checkout@v2
      - name: Auto-merge new events with known submitters
        uses: ./.github/actions/automerger
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
