name: Experiment

on: 
  check_suite:
  check_run:
  workflow_run:
    workflows: [Test]
    types:
      - completed

  
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: echo '${{ toJSON(github.event) }}'
